### ISSUE TITLE
Azure deployment name

### ISSUE THREAD

**Issue by bderenzi** [dimagi/open-chat-studio#121]
With Azure we're now getting a `openai.error.InvalidRequestError` error. [According to a bot](https://github.com/langchain-ai/langchain/issues/7470#issuecomment-1628780017), the issue is likely that we're not using a deployment name.

In our code, I don't think we're sending the correct arguments:
https://github.com/dimagi/open-chat-studio/blob/ee97e9bbec75c876b694684968c6d8df309edd31/apps/service_providers/llm_service.py#L56-L62

According to the [LangChain docs](https://python.langchain.com/docs/integrations/chat/azure_chat_openai):
```python
BASE_URL = "https://${TODO}.openai.azure.com"
API_KEY = "..."
DEPLOYMENT_NAME = "chat"
model = AzureChatOpenAI(
    openai_api_base=BASE_URL,
    openai_api_version="2023-05-15",
    deployment_name=DEPLOYMENT_NAME,
    openai_api_key=API_KEY,
    openai_api_type="azure",
)
```

**Comment by snopoke** [comment]
Interesting - these classes are confusing. So basically `deployment_name` is the same as `model` in OpenAI? If we add this to the service provider config you wan't be able to use different models with different experiments. 

What about changing (Experiment.llm](https://github.com/dimagi/open-chat-studio/blob/0e4639f5e6907e73ca9e651345add9283692e525/apps/experiments/models.py#L236) to allow you to specify any model name instead of restricting to a specific set - or we could have a preset list per provider?

**Comment by bderenzi** [comment]
(It's not clear to me that `LangChain` is a net win)

I think that `deployment_name` is `model`. I do think we need a per-provider list based on provider type. For example, Azure uses `gpt-35-turbo`, but OpenAI uses `gpt-3.5-turbo`. 

While we're there (or maybe as a separate issue), we'll want to make this user configurable. OpenAi uses a different model name to denote fine-tuned models.
