### ISSUE TITLE
History limits at the experiment level

### ISSUE THREAD

**Issue by bderenzi** [dimagi/open-chat-studio#141]
GPT-4 turbo has a context size of 128k. If a conversation went on long enough unchecked it would cost $1280 at current pricing just to read the input tokens.

I think we should limit context size, configured at an experiment level, to prevent runaway costs. We could choose to use LangChain's history compression or not. I'd vote for a simple thing for now because this is an edge case we just want to protect against. 

OpenAI's Assistant API is stateful and does something to compress history in the background. It's not clear to me exactly how this works (I couldn't find anything in the docs, but didn't dig too hard). Despite that, this may be appropriate for longer deployments so we may not want to invest too much effort into how we compress history just yet.

Note: we've hit the 8k limit numerous times operating in Chichewa, which is a token-dense language. If the gpt-4 limit of 8k hadn't existed those conversations could have continued in an increasingly expensive manner.

**Comment by snopoke** [comment]
I did some digging into this and it's not possible to use the Langchain summarization classes direction because they only work with in-memory conversations. To implement this ourselves could be done in 2 ways:

### Continuous summarization

Before each LLM call we check the size and if it's too large we prune messages and summarize them.

Pros:
- Simple

Cons:
- Since we're summarizing on every call we could rack up more costs.
- Once the total token length get's past 2 x max_tokens we end up where the pruned messages are also past max tokens and so we need to recursively summarize or use some other strategy

### Stored summarization

Similar to above but we store the summaries and add the to the history each time.

Pros:
- Doesn't require summarization on every call
- Won't require recursive summarization

Cons:
- More complex to implement
- Some unknown design elements e.g. how many messages to keep at the end of a thread when summarizing. The langchain model keeps as many as will fit in the context but that also means you end up summarizing a lot more frequently.
