### ISSUE TITLE
Deleting teams doesn't work

### ISSUE THREAD

**Issue by bderenzi** [dimagi/open-chat-studio#186]
I created a test team, invited my gmail, then tried to delete the team. Not sure if it's relevant that there was a pending invite. Anyway, here's the recursion error:

https://dimagi.sentry.io/issues/4806050600/?alert_rule_id=14063560&alert_timestamp=1704364280155&environment=production&notification_uuid=f5834af6-e852-454b-91f3-577757112f20&project=4505001320316928

**Comment by SmittieC** [comment]
This is related to the [audit library](https://github.com/dimagi/django-field-audit) we're using. I get a "maximum recursion depth exceeded" when trying to delete an audited model. I've only found this happening with deletions, and only on models that have some sort of relationship with another one, but I suspect there must be multiple relationships to trigger this. We can expect the models ticked on [this list](https://github.com/dimagi/open-chat-studio/issues/144#issuecomment-1851437110) to have this behaviour. My gut feeling says it should be fine to leave this as-is for now, since logging is more important than deleting stuff, but I'm happy to temporarily remove auditing if need be @bderenzi.

**Comment by SmittieC** [comment]
Reproduced the error in the audit library here: https://github.com/dimagi/django-field-audit/compare/cs/max_recursion_error?expand=1

**Comment by SmittieC** [comment]
This is fixed
