### ISSUE TITLE
Warn users about multiple `{source_material}` tags in prompt

### ISSUE THREAD

**Issue by bderenzi** [dimagi/open-chat-studio#581]
Source material is confusing to people. I often see our team write things like:

```txt
Refer to the information in {source_material} to better understand your persona.
```

Not only is that not ideal because it gets injected into the middle of a sentence, but we also allow multiple `{source_material}` tags in the prompt, potentially duplicating huge amounts of material.

I don't know how to solve the inline source material problem, but we should at least warn people about how multiple tags and duplication.

**Comment by SmittieC** [comment]
[PR](https://github.com/dimagi/open-chat-studio/pull/583) to disallow duplicates. This will "break" some experiments in the sense that users will not be able toupdate the experiment without first addressing the issue. 

> I don't know how to solve the inline source material problem

All I can think of is to have a prompt preview view somewhere, but just to solve this problem? A big squeeze for a little lemon :lemon: ...

So the issue is that people see the inclusion of this variable as a attachement with a reference to it. Like one would reference a file. Would it make sense to use it that way maybe? So if there is a source material variable in the prompt, we don't simply replace it in-place with the source material, but rather refer to a section that we append at the end of the prompt with the source material. Two thoughts on this:
1. A preview view would again be useful here
2. A concern is that we're then changing the prompt in a potential unpredictable way. I think...
