### ISSUE TITLE
Verify that events are using the correct experiment version

### ISSUE THREAD

**Issue by snopoke** [dimagi/open-chat-studio#987]
e.g. should this be getting the published version: https://github.com/dimagi/open-chat-studio/blob/f598270b25824597a3d4381aea4d31454456fd77/apps/events/models.py#L360

**Comment by SmittieC** [comment]
We don't currently update existing scheduled messages' `action` link if the action params between versions changes. For example say a user wants scheduled messages to happen daily instead of the initially configured weekly, but there's already some existing scheduled messages -> we don't do anything with them. They will continue to use the old action params.

I think in this case we should prompt the user to decide what to do
